on: [push]

jobs:
  grid_env_run:
    runs-on: ubuntu-latest
    name: grid-env run
    steps:
      - uses: actions/checkout@v2     
      - uses: robert-s-lee/gridai_action_login@main
        with:
          username: ${{ secrets.GRIDAI_USERNAME }} 
          key: ${{ secrets.GRIDAI_KEY }}       
      - id: run
        uses: robert-s-lee/gridai_action_run@main
        with:
          script_name: argecho.py 
      - run: |
          if [ "${{ steps.run.outputs.obj_status }}"" != "succeeded" ]; then
            exit 1
          fi


