# examples from https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
# list of actions available https://github.com/actions
name: "gridai-login"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  # run at 1:13 AM every day
  # MIN HOUR DOM MON DOW CMD
    - cron: '13 1 * * *'

jobs:
  gridlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # min version supported by Grid.ai
      - run: |
          python -m pip install --upgrade pip
      - run: |
          pip install lightning-grid --upgrade
      - run: |
          grid login --username ${{ secrets.GRIDAI_USERNAME }} --key ${{ secrets.GRIDAI_KEY }}   
      - run: |
          grid run --dependency_file requirements.txt argecho.py | tee /tmp/grid.run.log
          RUN_NAME=$(grep grid_name /tmp/grid.run.log | cut -d':' -f 2 | sed -e 's/^[[:space:]]*//')
          JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}')
          while [ "$(cat ${JSON_FILE} | jq -c '.[] | .status')" = '"queued"' ]; do echo waiting; JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}'); sleep 60; done
      - run: |
          grid artifacts ${RUN_NAME}
          ls
